version: '3.8'

services:
  nginx:
    image: nginx
    links:
      - sspanel
    volumes:
      - ./docker-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-site.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./data/sockets/php8.2-fpm.sock:/run/php/php8.2-fpm.sock:ro
      - ./:/var/www/html
    ports:
      - "8081:80"
    command: [nginx, '-g', 'daemon off;']

  sspanel:
    build: .
    depends_on:
      - mariadb
    volumes:
#      - ./data/sockets/php8.2-fpm.sock:/run/php/php8.2-fpm.sock
      - ./data/sockets/mariadb:/var/run/mysqld:ro
      - ./:/var/www/html

  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: examplepasswordboom
      MYSQL_DATABASE: sspanel
      MYSQL_USER: sspanel
      MYSQL_PASSWORD: sspanel
#    ports:  # use socket instead
#      - "3306:3306"
    volumes:
      - ./data/sockets/mariadb:/var/run/mysqld
      - ./sql/glzjin_all.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # TODO: map db file for persistent storage


volumes:
  db:
  site:

networks:
  default:
    name: sspanel_network
    driver: bridge
